### ISSUE TITLE
undefined method 'klas' for nil:NilClass Did you mean? class

### ISSUE THREAD

**Issue by Lubmes** [yzhanginwa/rails-simple-search#13] opened 2017-02-23 10:46 UTC
This is what we get using your gem after making a search.

What could this be?

**Comment by yzhanginwa** [comment] 2017-02-28 02:59
Hello, thanks for letting me know the issue!

Please let me know which version you're using. Also please paste the full error message here.

**Comment by yzhanginwa** [comment] 2017-02-28 15:15
In most cases, this issue is caused by using the wrong association name. Please check your code again. I'll close this issue for now. If the problem still persists, please open a new issue and pastes the full error messages here.

**Closed by yzhanginwa** 2017-02-28 15:15 UTC
